import { StyleSheet } from "react-native";

export const colors = {
  bg: "#07111d",
  card: "#0d1b2a",
  panel: "#12263b",
  border: "#1f3956",
  text: "#f8fbff",
  muted: "#a7bad1",
  accent: "#f4c84b",
  green: "#1f7a53",
  lightGreen: "#76d39b",
  yellow: "#f4c84b",
  red: "#c24e56",
  gray: "#7b8695",
};

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  pad: { padding: 16 },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    marginHorizontal: 14,
    marginTop: 12,
  },
  h1: { color: colors.text, fontSize: 24, fontWeight: "900" },
  h2: { color: colors.text, fontSize: 18, fontWeight: "900" },
  small: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  label: { color: colors.text, fontSize: 13, fontWeight: "800", marginTop: 14, marginBottom: 6 },
  input: {
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    color: colors.text,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  btn: {
    backgroundColor: colors.accent,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  btnText: { color: "#0b1220", fontWeight: "900", fontSize: 14 },
  btnGhost: {
    backgroundColor: colors.panel,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  btnGhostText: { color: colors.text, fontWeight: "900", fontSize: 14 },
  row: { flexDirection: "row", alignItems: "center" },
  listItem: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
  },
  listTitle: { color: colors.text, fontWeight: "900", fontSize: 16 },
  listSub: { color: colors.muted, fontSize: 13, marginTop: 4, lineHeight: 18 },
  chip: { borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: colors.panel },
  chipTxt: { color: colors.text, fontWeight: "800", fontSize: 12 },
});
